//! Markdown renderer for `Report`.

use crate::{Report, Severity};

pub(crate) fn render(report: &Report) -> String {
    let mut out = String::new();
    let p = &report.program;

    // Header
    out.push_str(&format!(
        "# Praxis Pre-Audit Report — {}\n\n",
        p.name
    ));
    out.push_str(&format!(
        "**Program ID:** `{}`  \n**Version:** {}  \n**Generated:** {}  \n\n",
        p.program_id, p.version, report.generated_at
    ));

    // Summary table
    out.push_str("## Summary\n\n");
    out.push_str("| Severity | Count |\n|----------|-------|\n");
    out.push_str(&format!("| Critical | {} |\n", report.summary.critical));
    out.push_str(&format!("| High     | {} |\n", report.summary.high));
    out.push_str(&format!("| Medium   | {} |\n", report.summary.medium));
    out.push_str(&format!("| Info     | {} |\n", report.summary.info));
    out.push_str(&format!("| **Total**| **{}** |\n\n", report.summary.total));

    if report.findings.is_empty() {
        out.push_str("✅ **No findings. All checks passed.**\n\n");
    } else {
        // Findings by severity
        out.push_str("## Findings\n\n");
        for sev in [Severity::Critical, Severity::High, Severity::Medium, Severity::Info] {
            let group: Vec<_> = report.findings.iter().filter(|f| f.severity == sev).collect();
            if group.is_empty() {
                continue;
            }
            out.push_str(&format!("### {} Severity\n\n", sev));
            for (i, f) in group.iter().enumerate() {
                out.push_str(&format!("#### [{sev}] {} — Finding {}\n\n", f.id, i + 1));
                out.push_str(&format!("**Message:** {}  \n", f.message));
                if let Some(loc) = &f.location {
                    out.push_str(&format!("**Location:** `{loc}`  \n"));
                }
                if let Some(seed) = &f.replay_seed {
                    out.push_str(&format!(
                        "**Reproduce:** `praxis replay --seed {seed}`  \n"
                    ));
                }
                out.push('\n');
            }
        }
    }

    // CU Profile section
    if let Some(profile) = &report.profile {
        out.push_str("## CU Profile\n\n");
        out.push_str("| Instruction | Avg CU | Max CU | % of Total |\n");
        out.push_str("|-------------|--------|--------|------------|\n");
        for ix in profile {
            out.push_str(&format!(
                "| `{}` | {} | {} | {:.1}% |\n",
                ix.name, ix.avg_cu, ix.max_cu, ix.pct_of_total
            ));
        }
        out.push('\n');
    }

    // Footer
    out.push_str("---\n\n");
    out.push_str(
        "*Generated by [Praxis](https://github.com/praxis-rs/praxis) — \
         Solana program testing and fuzzing framework.*\n",
    );

    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::{FindingSummary, ProgramMeta, Report, ReportFinding};

    fn make_report(findings: Vec<ReportFinding>) -> Report {
        let summary = FindingSummary {
            total: findings.len(),
            high: findings.iter().filter(|f| f.severity == Severity::High).count(),
            ..Default::default()
        };
        Report {
            schema_version: "1".into(),
            program: ProgramMeta {
                name: "test".into(),
                program_id: "1111".into(),
                version: "0.1.0".into(),
            },
            summary,
            findings,
            profile: None,
            generated_at: "2026-05-07T00:00:00Z".into(),
        }
    }

    #[test]
    fn empty_report_renders_ok() {
        let report = make_report(vec![]);
        let md = render(&report);
        assert!(md.contains("No findings"));
        assert!(md.contains("test"));
    }

    #[test]
    fn finding_renders_with_id_and_severity() {
        let report = make_report(vec![ReportFinding {
            id: "AC-001".into(),
            severity: Severity::High,
            message: "Missing signer".into(),
            location: Some("release::authority".into()),
            replay_seed: Some("deadbeef".into()),
        }]);
        let md = render(&report);
        assert!(md.contains("AC-001"));
        assert!(md.contains("Missing signer"));
        assert!(md.contains("praxis replay --seed deadbeef"));
    }
}
